version: '3'
services:
    postgres:
        container_name: recipes-postgres
        image: postgres:latest
        ports:
            - '5432:5432'
        volumes:
            - ./data/postgres:/data/recipes-postgres
        env_file:
            - docker.env

    postgres-test:
        container_name: recipes-postgres-test
        image: postgres:latest
        ports:
            - '5433:5432'
        volumes:
            - ./data/postgres:/data/recipes-postgres-test
        env_file:
            - docker.test.env
